# Generated by Django 4.2.1 on 2023-05-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('size', models.CharField(choices=[('150', '150G'), ('200', '200G')], default='150G', max_length=5)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
