# Generated by Django 4.2.1 on 2023-05-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='size',
            field=models.CharField(choices=[('150', '150G'), ('200', '200G')], default='150G', max_length=5),
        ),
    ]
